### ISSUE TITLE
Implement http.Hijacker to support interaction with Websockets

### ISSUE THREAD

**Issue by durdn** [NYTimes/gziphandler#26]
Hey there,

You wrote a fantastic library and I've been using it with pleasure so far.

I have run into an issue when using the `GzipHandler` and `gorilla/websocket` (and I saw reports of similar failures for `code.google.com/p/go.net/websocket`):

I run into this:

`websocket: response does not implement http.Hijacker`

It seems the response interface of your library does not implement http.Hijacker which is needed to use websockets.

The fix appears relatively easy and several other libraries have implemented a fix. For example:

https://github.com/mholt/caddy/commit/05957b4965413bccac8a7e24dc8f5314f15a278b

https://github.com/gin-gonic/gin/pull/105/files

Other useful thread:
https://github.com/gin-gonic/gin/issues/51

I probably can work around my problem by not using the GzipHandler in bulk for all my routes but I thought you'd be interested in the problem and possibly copy the fixes above.

**Comment by durdn** [comment]
@jprobinson Let me just say this response speed is incredible. Thanks a lot!

**Comment by jprobinson** [comment]
This one was all @brianfoshee. Thanks for using the lib!!

**Comment by durdn** [comment]
Oh right Thanks a lot to @brianfoshee !!
