### ISSUE TITLE
Invalid number of bytes written reported

### ISSUE THREAD

**Issue by mikegleasonjr** [NYTimes/gziphandler#44]
When I have a buffer of a known length and try to write to the gzip handler, I get more bytes written than I originally sent. It think the latest commit is causing that.

```
b := f.buf[f.off:]
l := len(b)           // l is 104870
n, err := w.Write(b)  // w is my gziphandler (writer)
                      // n is 105079
```

**Comment by adammck** [comment]
Is this still the case since #42 was merged?

**Comment by mikegleasonjr** [comment]
Oh wow sorry I was 1 commit behind, didn't notice you did another commit after #41 👍

**Comment by adammck** [comment]
No problem, sorry about all the fuss.
