### ISSUE TITLE
export acceptsGzip?

### ISSUE THREAD

**Issue by jmackie4** [NYTimes/gziphandler#48]
Is there any particular reason for not exporting the `acceptsGzip` function? 

I'm running a static file handler that serves pre-gzipped files, and it would be really useful to have access to the logic of this function for that use case. 

More of a suggestion than an issue, apologies. 

Great package btw! :+1:

**Comment by adammck** [comment]
I have no problem with this, but there's a more complete implementation [in gddo](https://github.com/golang/gddo/blob/master/httputil/header/header.go#L172) which you might find useful. I've been meaning to switch to this some time, but I haven't received any complaints about our implementation, so haven't gotten around to it.

**Comment by adammck** [comment]
See also #34.
