### ISSUE TITLE
How do you implement this in a Gin server?

### ISSUE THREAD

**Issue by SkyrisBactera** [NYTimes/gziphandler#57]

**Comment by jprobinson** [comment]
Hi there, @SkyrisBactera!

I haven't tried it myself, but it looks like folks have created a tool that may allows users to hook in an `http.Handler` middleware: https://github.com/turtlemonvh/gin-wraphh

Check here for more info: https://github.com/gin-gonic/gin/issues/293

I hope this helps. If not, please create an issue with the gin project.

**Comment by SkyrisBactera** [comment]
Thank you for such a quick response! I'll try it out! Thanks!

**Comment by SkyrisBactera** [comment]
For anybody else looking at this, you want to use
```go
router.Use(wraphh.WrapHH(gziphandler.GzipHandler))
```
after importing
```go
"github.com/turtlemonvh/gin-wraphh"
```
