### ISSUE TITLE
make acceptsGzip public

### ISSUE THREAD

**Issue by meirf** [NYTimes/gziphandler#65]
It would make my use of this library much easier if my code can see whether the library will consider a request for possible compression. 

Would making [`acceptsGzip`](https://github.com/NYTimes/gziphandler/blob/master/gzip.go#L350) -> `AcceptsGzip` as a pull request be welcome?

**Comment by jprobinson** [comment]
I think this has popped up a few times so I'm into adding the option to alter the default.

Instead of making that func public, perhaps we can add a `func AcceptsGzip(func(*http.Request) bool) option` to let folks optionally extend it?

Would that fit your use case?

**Comment by meirf** [comment]
That is a slick api addition and I could see it being useful to other, but I don't have an issue with the way it is determining compression. I just want to access the logic independently of the way the public api uses it. Feel free to change the title of this issue/repurpose/close for `AcceptsGzip`.

**Comment by adammck** [comment]
This is a dupe of #34 and #48, and I think the same recommendation applies. I don't see any problem with to exporting the func, but there's already a better implementation [in gddo](https://github.com/golang/gddo/blob/master/httputil/header/header.go#L172).

**Comment by tmthrgd** [comment]
@meirf I have an implementation based on [gddo](https://github.com/golang/gddo/blob/master/httputil/header/header.go#L172) available at [tmthrgd/httputils](https://godoc.org/github.com/tmthrgd/httputils#Negotiate) if that's useful to you.
