### ISSUE TITLE
Whitelist by mime type

### ISSUE THREAD

**Issue by meirf** [NYTimes/gziphandler#68]
[ContentTypes(types []string) option](https://godoc.org/github.com/NYTimes/gziphandler#ContentTypes) whitelists by the full content type. In my case, the encoding and boundary don't matter to me. All I care about is the MIME type. I'd rather not have to declare all the encodings for each MIME type.

Is there an interest in accepting a PR which adds something like one of these:
- `ContentTypesMimeOnly(types []string) option` 
- `MimeTypes(types []string) option`

This would use the [standard method](https://play.golang.org/p/HbYkyD7HebL) for parsing the mime type.

(@jprobinson, @adammck do you have thoughts on this?)

**Comment by meirf** [comment]
@jprobinson, thought on this?

**Comment by meirf** [comment]
@tmthrgd opinion on this?

**Comment by jprobinson** [comment]
Could we perhaps make just 1 new option, `func AcceptsGzip(func(*http.Request) bool) option` and then folks can do whatever they please within it?

**Comment by adammck** [comment]
I agree that we should have an Accepts option as @jprobinson suggests, but I suspect that the most common usage of that would be to implement MimeTypes([]string). So perhaps we should just add that option, too. In hindsight, that seems more useful than ContentTypes. Maybe deprecate that.

**Comment by jprobinson** [comment]
From what our wise friend @adammck says, I think the `MimeTypes(types []string) option` would be worth bringing in but if you have the will to make all of the above, go for it.

**Comment by tmthrgd** [comment]
I'd be in favour of this. :+1:

In [my fork](https://github.com/tmthrgd/gziphandler) this is how I chose to implement [ContentTypes](https://github.com/tmthrgd/gziphandler/blob/master/gzip.go#L460-L476) already. (See [here](https://github.com/tmthrgd/gziphandler/blob/master/gzip.go#L245-L264) and [here](https://github.com/tmthrgd/httputils/blob/master/mime-type.go#L22-L62)).

It looks like the existing behaviour is somewhat broken anyway. `text/html;charset=utf-8` won't match `text/html; charset=utf-8` (note the space), yet they are semantically identical.

I also can't see a situation where *anyone* would depend on, say, compressing `charset=utf-8` but *not* compressing `charset=us-ascii`.

My one concern is the proliferation of exported symbols in this package (compare [NYTimes/gziphandler](https://godoc.org/github.com/NYTimes/gziphandler) with [tmthrgd/gziphandler](https://godoc.org/github.com/tmthrgd/gziphandler)). Considering the documentation of `ContentTypes` doesn't explicitly state it's behaviour, perhaps it would be acceptable to change `ContentTypes` to strip the directives and whitespace before comparisions.

That's my 2c anyway.

**Comment by meirf** [comment]
I’ve uploaded a PR with what I think are the best ideas y’all have presented: not changing the api, ignoring white space and allowing mime-only comparison.

One thing I didn’t include was text/*. Though some people might not differentiate between text/plain and text/html, I think some would. But more importantly this type of pattern leaves the comfort of the standard library’s parsing and has much higher likelihood of introducing bugs.

**Comment by meirf** [comment]
Merged https://github.com/NYTimes/gziphandler/pull/69
Thanks!
