### ISSUE TITLE
The NYTimes GitHub org will be renamed to nytimes

### ISSUE THREAD

**Issue by gkilleen** [nytimes/gziphandler#78]
Users / Importers of gziphandler, please note that the `github.com/NYTimes` org (where this repo resides) will be renamed to all lowercase `github.com/nytimes`.  This branding change is for readability and to conform with the majority of other GitHub entities and open source projects.

When the organization name changes, users will still be able to download, import, and use any of our NYTimes libraries with the old casing (NYTimes). Therefore, there shouldn’t be any action taken on the user’s side as long as you have your dependencies managed through Go Modules or Dep.

However, once the github name changes, we will also be updating the import paths in the actual code of those libraries. Once that code is committed, we will tag a major version release. This way, users know that if they want to know this update is a breaking change and they would have to update their own import paths too. 

In Go Modules, you will need to change the import path to lowercase `NYTimes` to `nytimes` and also ensure the import path includes the major version per Semantic Import Versioning rules.

The proposed date for the rename will happen **during the week of March 4, 2019**.

**Comment by gkilleen** [comment]
Please note this rename occurred on March 4, 2019 at 11:35AM EST.

**Comment by barbashov** [comment]
Hello and thanks for the great package!

This rename seems to lead to an issue: running `go build` (go 1.12) for a project depending on the package gives the following error:
```
go: github.com/nytimes/gziphandler@v1.1.1: parsing go.mod: unexpected module path "github.com/NYTimes/gziphandler"
go: error loading module requirements
```

I suppose go.mod should feature lowercase `nytimes` now as well?

**Comment by barbashov** [comment]
Please consider PR #82

**Comment by fsouza** [comment]
@barbashov that's a breaking change, so we'd need to tag a new 

Can you share your ``go.mod`` file? Or just the line that has gziphandler, really. If your code uses the import path ``github.com/NYTimes/gziphandler`` and ``go.mod`` ``require``s the path path NYTimes, everything _should_ work fine.
