### ISSUE TITLE
Align Go package casing with VCS URL casing

### ISSUE THREAD

**Issue by mcandre** [nytimes/gziphandler#85]
Can we have the Go package name match casing with the version control URL casing? This subtle difference makes it harder to manage dependencies.

If backwards compatibility is a concern lol, it would actually be easier to rename the GitHub org, which users would reference just once, compared to having to rename every downstream import.

**Comment by jprobinson** [comment]
Our org actually used to be the mixed camel case we use in the imports for the library. 

We maintain the old casing for the sake of backwards compatibility. You’ll notice almost all of our open source offerings follow the same casing scheme.

If we do change the case in the future, it would be a breaking change. We may do this as libraries approach v2.0.0 when import paths for Modules changes but there is no immediate plans for that right now.

We do provide documentation in our README to point folks in the right direction: https://github.com/nytimes/gziphandler/blob/master/README.md#install
